[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lynx_data_pipeline"
version = "0.1.0"
dependencies = [
    "dagster",
    "dagster-webserver",
    "pandas",
]

[tool.dagster]
module_name = "src.definitions"
